### ISSUE TITLE
FWD Site Down

### ISSUE THREAD

**Issue by kasumaz** [MaayanLab/L1000FWD#6]
Hi there, 
Is the site L1000FWD http://amp.pharm.mssm.edu/l1000fwd/#   down? 
I have been trying to use it to finish off some work for submission, but there are errors when clicking submit with gene signitures. 
Let me know when I could use it again.
Many thanks.

**Comment by AviMaayan** [comment]
@kasumaz thanks to @u8sand it is now fixed!

**Comment by kasumaz** [comment]
Many thanks

**Comment by kasumaz** [comment]
Hi its me again. I was using it lately again last week. Was fine. It seems down again in the same way as before. No rush to fix. I just thought to let you know. I can come back to it later. Thanks.

**Comment by u8sand** [comment]
l1000fwd is part of an external health check, it should restart within 10 minutes if it goes down.. FYI. Unfortunately this app goes down a lot.

-- edit --

or rather, this is the case if you get a 503 error. The connection error with R is harder to detect a failure as R doesn't die it just stalls. Should be up again now..

**Comment by kasumaz** [comment]
Hi thanks a lot for working on it so fast. its working again. have a good day.
